#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hardinfo
Version  : 83de522ed44c719ba887935893b8c97b005d47fd
Release  : 5
URL      : https://github.com/lpereira/hardinfo/archive/83de522ed44c719ba887935893b8c97b005d47fd.tar.gz
Source0  : https://github.com/lpereira/hardinfo/archive/83de522ed44c719ba887935893b8c97b005d47fd.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: hardinfo-bin = %{version}-%{release}
Requires: hardinfo-data = %{version}-%{release}
Requires: hardinfo-lib = %{version}-%{release}
Requires: hardinfo-license = %{version}-%{release}
Requires: hardinfo-locales = %{version}-%{release}
Requires: hardinfo-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-png)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-export-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(x11)
Patch1: fix-enum-declaration.patch

%description
This is Christian Hergert's "Uber-Graph"
after commit d31c8014d8cc9f293dfecfcb4bd6a7bf4d61c0be.
https://gitlab.gnome.org/chergert/uber-graph
File headers give LGPL2 as the license.

%package bin
Summary: bin components for the hardinfo package.
Group: Binaries
Requires: hardinfo-data = %{version}-%{release}
Requires: hardinfo-license = %{version}-%{release}

%description bin
bin components for the hardinfo package.


%package data
Summary: data components for the hardinfo package.
Group: Data

%description data
data components for the hardinfo package.


%package lib
Summary: lib components for the hardinfo package.
Group: Libraries
Requires: hardinfo-data = %{version}-%{release}
Requires: hardinfo-license = %{version}-%{release}

%description lib
lib components for the hardinfo package.


%package license
Summary: license components for the hardinfo package.
Group: Default

%description license
license components for the hardinfo package.


%package locales
Summary: locales components for the hardinfo package.
Group: Default

%description locales
locales components for the hardinfo package.


%package man
Summary: man components for the hardinfo package.
Group: Default

%description man
man components for the hardinfo package.


%prep
%setup -q -n hardinfo-83de522ed44c719ba887935893b8c97b005d47fd
cd %{_builddir}/hardinfo-83de522ed44c719ba887935893b8c97b005d47fd
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589904846
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DHARDINFO_GTK3=1 -DCMAKE_INSTALL_LIBDIR=lib64
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1589904846
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/hardinfo
cp %{_builddir}/hardinfo-83de522ed44c719ba887935893b8c97b005d47fd/LICENSE %{buildroot}/usr/share/package-licenses/hardinfo/d6458d52bfead6f1399b865f1aeea0caa639ef6c
pushd clr-build
%make_install
popd
%find_lang hardinfo

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hardinfo

%files data
%defattr(-,root,root,-)
/usr/share/applications/hardinfo.desktop
/usr/share/hardinfo/benchmark.conf
/usr/share/hardinfo/benchmark.data
/usr/share/hardinfo/doc/index.hlp
/usr/share/hardinfo/pixmaps/about-modules.png
/usr/share/hardinfo/pixmaps/audio.png
/usr/share/hardinfo/pixmaps/battery.png
/usr/share/hardinfo/pixmaps/benchmark.png
/usr/share/hardinfo/pixmaps/blowfish.png
/usr/share/hardinfo/pixmaps/bluetooth.png
/usr/share/hardinfo/pixmaps/boot.png
/usr/share/hardinfo/pixmaps/camera-photo.png
/usr/share/hardinfo/pixmaps/camera-web.png
/usr/share/hardinfo/pixmaps/cdrom.png
/usr/share/hardinfo/pixmaps/close.png
/usr/share/hardinfo/pixmaps/compress.png
/usr/share/hardinfo/pixmaps/computer.png
/usr/share/hardinfo/pixmaps/cryptohash.png
/usr/share/hardinfo/pixmaps/dev_removable.png
/usr/share/hardinfo/pixmaps/devel.png
/usr/share/hardinfo/pixmaps/devices.png
/usr/share/hardinfo/pixmaps/dialog-error.png
/usr/share/hardinfo/pixmaps/dialog-information.png
/usr/share/hardinfo/pixmaps/dialog-warning.png
/usr/share/hardinfo/pixmaps/dns.png
/usr/share/hardinfo/pixmaps/environment.png
/usr/share/hardinfo/pixmaps/face-grin.png
/usr/share/hardinfo/pixmaps/fft.png
/usr/share/hardinfo/pixmaps/file-roller.png
/usr/share/hardinfo/pixmaps/hardinfo.png
/usr/share/hardinfo/pixmaps/hdd.png
/usr/share/hardinfo/pixmaps/home.png
/usr/share/hardinfo/pixmaps/inputdevices.png
/usr/share/hardinfo/pixmaps/internet.png
/usr/share/hardinfo/pixmaps/joystick.png
/usr/share/hardinfo/pixmaps/keyboard.png
/usr/share/hardinfo/pixmaps/language.png
/usr/share/hardinfo/pixmaps/logo.xcf
/usr/share/hardinfo/pixmaps/media-floppy.png
/usr/share/hardinfo/pixmaps/media-removable.png
/usr/share/hardinfo/pixmaps/memory.png
/usr/share/hardinfo/pixmaps/modem.png
/usr/share/hardinfo/pixmaps/module.png
/usr/share/hardinfo/pixmaps/monitor.png
/usr/share/hardinfo/pixmaps/mouse.png
/usr/share/hardinfo/pixmaps/nautilus.png
/usr/share/hardinfo/pixmaps/network-connections.png
/usr/share/hardinfo/pixmaps/network-interface.png
/usr/share/hardinfo/pixmaps/network-statistics.png
/usr/share/hardinfo/pixmaps/network.png
/usr/share/hardinfo/pixmaps/nqueens.png
/usr/share/hardinfo/pixmaps/os.png
/usr/share/hardinfo/pixmaps/pcmcia.png
/usr/share/hardinfo/pixmaps/printer.png
/usr/share/hardinfo/pixmaps/processor.png
/usr/share/hardinfo/pixmaps/raytrace.png
/usr/share/hardinfo/pixmaps/report-large.png
/usr/share/hardinfo/pixmaps/report.png
/usr/share/hardinfo/pixmaps/resources.png
/usr/share/hardinfo/pixmaps/security.png
/usr/share/hardinfo/pixmaps/server-large.png
/usr/share/hardinfo/pixmaps/server.png
/usr/share/hardinfo/pixmaps/shares.png
/usr/share/hardinfo/pixmaps/summary.png
/usr/share/hardinfo/pixmaps/syncmanager-small.png
/usr/share/hardinfo/pixmaps/syncmanager.png
/usr/share/hardinfo/pixmaps/therm.png
/usr/share/hardinfo/pixmaps/usb.png
/usr/share/hardinfo/pixmaps/usbfldisk.png
/usr/share/hardinfo/pixmaps/users.png
/usr/share/hardinfo/pixmaps/wireless.png
/usr/share/hardinfo/vendor.ids
/usr/share/icons/hicolor/48x48/apps/hardinfo.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/hardinfo/modules/benchmark.so
/usr/lib64/hardinfo/modules/computer.so
/usr/lib64/hardinfo/modules/devices.so
/usr/lib64/hardinfo/modules/network.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/hardinfo/d6458d52bfead6f1399b865f1aeea0caa639ef6c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/hardinfo.1

%files locales -f hardinfo.lang
%defattr(-,root,root,-)

